USE tasksDB;

CREATE TABLE tasks (
    id INT PRIMARY KEY AUTO_INCREMENT, task_name VARCHAR(20) NOT NULL, date DATE DEFAULT(CURRENT_TIMESTAMP), limit_date DATE NOT NULL
);

CREATE TABLE tasks_options (
    task_id INT NOT NULL, urgent BOOLEAN NOT NULL DEFAULT(0), important BOOLEAN NOT NULL DEFAULT(0), FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE
);

CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT, user_name VARCHAR(12) NOT NULL UNIQUE, email VARCHAR(50) NOT NULL
);

CREATE TABLE user_tasks (
    user_id INT NOT NULL, task_id INT NOT NULL, FOREIGN KEY (user_id) REFERENCES users (id), FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE
);